#ifndef ROMAN_NUMERALS_CONSECUTIVE_DIGIT_VERIFIER_H
#define ROMAN_NUMERALS_CONSECUTIVE_DIGIT_VERIFIER_H

char* is_roman_numeral_valid(char* roman);

#endif /* ROMAN_NUMERALS_CONSECUTIVE_DIGIT_VERIFIER_H */